"""remove models post.level

Revision ID: 0368b0da5433
Revises: c322ae4b5d69
Create Date: 2020-03-26 20:05:33.041070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0368b0da5433'
down_revision = 'c322ae4b5d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('blog_post', 'level')
    with op.batch_alter_table('blog_post') as batch_op:
        batch_op.drop_column('level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('level', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
