"""add ususer deal-2

Revision ID: 96425609ef7f
Revises: ac4d1984ea41
Create Date: 2020-03-14 23:08:25.244169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96425609ef7f'
down_revision = 'ac4d1984ea41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('is_active')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
