"""add ususer deal3

Revision ID: 9dfa14784b1b
Revises: 96425609ef7f
Create Date: 2020-03-15 20:34:37.822316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfa14784b1b'
down_revision = '96425609ef7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('invest_money', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'address')
    op.drop_column('deal', 'invest_money')
    # ### end Alembic commands ###
